### ISSUE TITLE
issue if woman has hair style in front side

### ISSUE THREAD

**Issue by sudip550** [TonyAssi/Segment-Clothing#1]
if a photo has hair in front side(on dress) then its look like 2 clothes. is there any way to do it better. 
![JNE4305-DR](https://github.com/TonyAssi/Segment-Clothing/assets/74753373/d91cfff1-536c-4661-8b89-7ba63f9f39e3)
![image (4)](https://github.com/TonyAssi/Segment-Clothing/assets/74753373/d85d3c94-5c17-4770-bdf3-d66aabe77dae)

**Comment by TonyAssi** [comment]
Technically, the model is performing its task. Its segmenting the clothes only.
